# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME_DEVELOPMENT'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] %>

test:
  <<: *default
  database: im_back_test

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['DATABASE_URL'] %>
    sslmode: require
  cache:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL']&.sub(/\?.*/, '') %>
  queue:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL']&.sub(/\?.*/, '') %>
  cable:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL']&.sub(/\?.*/, '') %>